
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 05 17:03:02 BRT 2011
//----------------------------------------------------

package compil.inv.parser;

import compil.inv.semantica.*;
import compil.inv.geracao.GeradorDeCodigo;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Jun 05 17:03:02 BRT 2011
  */
public class OclCup extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public OclCup() {super();}

  /** Constructor which sets the default scanner. */
  public OclCup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public OclCup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\125\000\002\046\002\000\002\002\005\000\002\002" +
    "\004\000\002\002\002\000\002\004\004\000\002\005\004" +
    "\000\002\006\003\000\002\006\005\000\002\006\005\000" +
    "\002\047\002\000\002\011\007\000\002\050\002\000\002" +
    "\011\010\000\002\011\002\000\002\007\003\000\002\013" +
    "\004\000\002\024\004\000\002\024\002\000\002\014\004" +
    "\000\002\025\004\000\002\025\002\000\002\015\004\000" +
    "\002\021\005\000\002\021\002\000\002\016\004\000\002" +
    "\022\005\000\002\022\002\000\002\017\004\000\002\017" +
    "\003\000\002\020\004\000\002\023\005\000\002\023\005" +
    "\000\002\023\002\000\002\010\003\000\002\010\003\000" +
    "\002\010\005\000\002\010\003\000\002\026\011\000\002" +
    "\034\004\000\002\045\004\000\002\041\003\000\002\041" +
    "\002\000\002\037\004\000\002\051\002\000\002\040\005" +
    "\000\002\052\002\000\002\040\006\000\002\040\003\000" +
    "\002\053\002\000\002\042\007\000\002\043\005\000\002" +
    "\043\002\000\002\003\010\000\002\003\004\000\002\003" +
    "\002\000\002\035\004\000\002\036\005\000\002\036\002" +
    "\000\002\012\003\000\002\012\003\000\002\012\003\000" +
    "\002\012\003\000\002\044\003\000\002\044\003\000\002" +
    "\044\003\000\002\044\003\000\002\044\003\000\002\044" +
    "\003\000\002\044\003\000\002\030\003\000\002\030\003" +
    "\000\002\031\003\000\002\031\003\000\002\027\003\000" +
    "\002\027\003\000\002\033\003\000\002\033\003\000\002" +
    "\033\003\000\002\033\003\000\002\032\003\000\002\032" +
    "\003\000\002\032\003\000\002\032\003\000\002\032\003" +
    "\000\002\032\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\203\000\006\002\ufffe\004\007\001\002\000\004\002" +
    "\205\001\002\000\010\002\ufff4\004\ufff4\005\021\001\002" +
    "\000\006\002\001\004\001\001\002\000\004\051\011\001" +
    "\002\000\010\002\ufffc\004\ufffc\005\ufffc\001\002\000\014" +
    "\002\ufffb\004\ufffb\005\ufffb\025\013\026\012\001\002\000" +
    "\004\051\015\001\002\000\004\051\014\001\002\000\010" +
    "\002\ufffa\004\ufffa\005\ufffa\001\002\000\010\002\ufff9\004" +
    "\ufff9\005\ufff9\001\002\000\006\002\ufffe\004\007\001\002" +
    "\000\004\002\000\001\002\000\006\002\ufffd\004\ufffd\001" +
    "\002\000\006\025\023\051\022\001\002\000\004\025\201" +
    "\001\002\000\024\011\027\021\047\027\034\035\033\051" +
    "\035\052\041\053\050\054\032\055\046\001\002\000\052" +
    "\002\uffea\004\uffea\005\uffea\006\uffea\007\uffea\010\uffea\012" +
    "\uffea\013\uffea\014\uffea\015\uffea\016\uffea\017\uffea\020\174" +
    "\021\175\030\uffea\034\uffea\036\uffea\037\uffea\040\uffea\041" +
    "\uffea\001\002\000\020\027\034\035\033\051\035\052\041" +
    "\053\050\054\032\055\046\001\002\000\046\002\uffed\004" +
    "\uffed\005\uffed\006\uffed\007\uffed\010\uffed\012\161\013\163" +
    "\014\165\015\167\016\164\017\166\030\uffed\034\uffed\036" +
    "\uffed\037\uffed\040\uffed\041\uffed\001\002\000\020\027\uffb7" +
    "\035\uffb7\051\uffb7\052\uffb7\053\uffb7\054\uffb7\055\uffb7\001" +
    "\002\000\064\002\uffd8\004\uffd8\005\uffd8\006\uffd8\007\uffd8" +
    "\010\uffd8\012\uffd8\013\uffd8\014\uffd8\015\uffd8\016\uffd8\017" +
    "\uffd8\020\uffd8\021\uffd8\022\uffd8\023\uffd8\027\103\030\uffd8" +
    "\032\uffd8\033\uffd8\034\uffd8\036\uffd8\037\uffd8\040\uffd8\041" +
    "\uffd8\001\002\000\056\002\uffe7\004\uffe7\005\uffe7\006\uffe7" +
    "\007\uffe7\010\uffe7\012\uffe7\013\uffe7\014\uffe7\015\uffe7\016" +
    "\uffe7\017\uffe7\020\uffe7\021\uffe7\022\152\023\154\030\uffe7" +
    "\034\uffe7\036\uffe7\037\uffe7\040\uffe7\041\uffe7\001\002\000" +
    "\062\002\uffc5\004\uffc5\005\uffc5\006\uffc5\007\uffc5\010\uffc5" +
    "\012\uffc5\013\uffc5\014\uffc5\015\uffc5\016\uffc5\017\uffc5\020" +
    "\uffc5\021\uffc5\022\uffc5\023\uffc5\030\uffc5\032\uffc5\033\uffc5" +
    "\034\uffc5\036\uffc5\037\uffc5\040\uffc5\041\uffc5\001\002\000" +
    "\024\011\027\021\047\027\034\035\033\051\035\052\041" +
    "\053\050\054\032\055\046\001\002\000\024\011\027\021" +
    "\047\027\034\035\033\051\035\052\041\053\050\054\032" +
    "\055\046\001\002\000\066\002\uffc8\004\uffc8\005\uffc8\006" +
    "\uffc8\007\uffc8\010\uffc8\012\uffc8\013\uffc8\014\uffc8\015\uffc8" +
    "\016\uffc8\017\uffc8\020\uffc8\021\uffc8\022\uffc8\023\uffc8\026" +
    "\114\027\uffc8\030\uffc8\032\uffc8\033\uffc8\034\uffc8\036\uffc8" +
    "\037\uffc8\040\uffc8\041\uffc8\001\002\000\062\002\uffdf\004" +
    "\uffdf\005\uffdf\006\uffdf\007\uffdf\010\uffdf\012\uffdf\013\uffdf" +
    "\014\uffdf\015\uffdf\016\uffdf\017\uffdf\020\uffdf\021\uffdf\022" +
    "\uffdf\023\uffdf\030\uffdf\032\uffdf\033\uffdf\034\uffdf\036\uffdf" +
    "\037\uffdf\040\uffdf\041\uffdf\001\002\000\062\002\uffe1\004" +
    "\uffe1\005\uffe1\006\uffe1\007\uffe1\010\uffe1\012\uffe1\013\uffe1" +
    "\014\uffe1\015\uffe1\016\uffe1\017\uffe1\020\uffe1\021\uffe1\022" +
    "\uffe1\023\uffe1\030\uffe1\032\063\033\065\034\uffe1\036\uffe1" +
    "\037\uffe1\040\uffe1\041\uffe1\001\002\000\056\002\uffe5\004" +
    "\uffe5\005\uffe5\006\uffe5\007\uffe5\010\uffe5\012\uffe5\013\uffe5" +
    "\014\uffe5\015\uffe5\016\uffe5\017\uffe5\020\uffe5\021\uffe5\022" +
    "\uffe5\023\uffe5\030\uffe5\034\uffe5\036\uffe5\037\uffe5\040\uffe5" +
    "\041\uffe5\001\002\000\062\002\uffc7\004\uffc7\005\uffc7\006" +
    "\uffc7\007\uffc7\010\uffc7\012\uffc7\013\uffc7\014\uffc7\015\uffc7" +
    "\016\uffc7\017\uffc7\020\uffc7\021\uffc7\022\uffc7\023\uffc7\030" +
    "\uffc7\032\uffc7\033\uffc7\034\uffc7\036\uffc7\037\uffc7\040\uffc7" +
    "\041\uffc7\001\002\000\032\002\ufff0\004\ufff0\005\ufff0\006" +
    "\061\007\060\010\057\030\ufff0\034\ufff0\036\ufff0\037\ufff0" +
    "\040\ufff0\041\055\001\002\000\022\002\ufff3\004\ufff3\005" +
    "\ufff3\030\ufff3\034\ufff3\036\ufff3\037\ufff3\040\ufff3\001\002" +
    "\000\062\002\uffdd\004\uffdd\005\uffdd\006\uffdd\007\uffdd\010" +
    "\uffdd\012\uffdd\013\uffdd\014\uffdd\015\uffdd\016\uffdd\017\uffdd" +
    "\020\uffdd\021\uffdd\022\uffdd\023\uffdd\030\uffdd\032\uffdd\033" +
    "\uffdd\034\uffdd\036\uffdd\037\uffdd\040\uffdd\041\uffdd\001\002" +
    "\000\010\002\ufff8\004\ufff8\005\ufff8\001\002\000\062\002" +
    "\uffc4\004\uffc4\005\uffc4\006\uffc4\007\uffc4\010\uffc4\012\uffc4" +
    "\013\uffc4\014\uffc4\015\uffc4\016\uffc4\017\uffc4\020\uffc4\021" +
    "\uffc4\022\uffc4\023\uffc4\030\uffc4\032\uffc4\033\uffc4\034\uffc4" +
    "\036\uffc4\037\uffc4\040\uffc4\041\uffc4\001\002\000\020\027" +
    "\uffb8\035\uffb8\051\uffb8\052\uffb8\053\uffb8\054\uffb8\055\uffb8" +
    "\001\002\000\062\002\uffc6\004\uffc6\005\uffc6\006\uffc6\007" +
    "\uffc6\010\uffc6\012\uffc6\013\uffc6\014\uffc6\015\uffc6\016\uffc6" +
    "\017\uffc6\020\uffc6\021\uffc6\022\uffc6\023\uffc6\030\uffc6\032" +
    "\uffc6\033\uffc6\034\uffc6\036\uffc6\037\uffc6\040\uffc6\041\uffc6" +
    "\001\002\000\062\002\uffe0\004\uffe0\005\uffe0\006\uffe0\007" +
    "\uffe0\010\uffe0\012\uffe0\013\uffe0\014\uffe0\015\uffe0\016\uffe0" +
    "\017\uffe0\020\uffe0\021\uffe0\022\uffe0\023\uffe0\030\uffe0\032" +
    "\uffe0\033\uffe0\034\uffe0\036\uffe0\037\uffe0\040\uffe0\041\uffe0" +
    "\001\002\000\010\002\ufff4\004\ufff4\005\021\001\002\000" +
    "\006\002\ufff7\004\ufff7\001\002\000\024\011\027\021\047" +
    "\027\034\035\033\051\035\052\041\053\050\054\032\055" +
    "\046\001\002\000\024\011\uffb3\021\uffb3\027\uffb3\035\uffb3" +
    "\051\uffb3\052\uffb3\053\uffb3\054\uffb3\055\uffb3\001\002\000" +
    "\022\002\ufff2\004\ufff2\005\ufff2\030\ufff2\034\ufff2\036\ufff2" +
    "\037\ufff2\040\ufff2\001\002\000\024\011\uffb6\021\uffb6\027" +
    "\uffb6\035\uffb6\051\uffb6\052\uffb6\053\uffb6\054\uffb6\055\uffb6" +
    "\001\002\000\024\011\uffb4\021\uffb4\027\uffb4\035\uffb4\051" +
    "\uffb4\052\uffb4\053\uffb4\054\uffb4\055\uffb4\001\002\000\024" +
    "\011\uffb5\021\uffb5\027\uffb5\035\uffb5\051\uffb5\052\uffb5\053" +
    "\uffb5\054\uffb5\055\uffb5\001\002\000\022\002\ufff1\004\ufff1" +
    "\005\ufff1\030\ufff1\034\ufff1\036\ufff1\037\ufff1\040\ufff1\001" +
    "\002\000\020\042\100\043\071\044\073\045\074\046\077" +
    "\047\075\050\070\001\002\000\056\002\uffe4\004\uffe4\005" +
    "\uffe4\006\uffe4\007\uffe4\010\uffe4\012\uffe4\013\uffe4\014\uffe4" +
    "\015\uffe4\016\uffe4\017\uffe4\020\uffe4\021\uffe4\022\uffe4\023" +
    "\uffe4\030\uffe4\034\uffe4\036\uffe4\037\uffe4\040\uffe4\041\uffe4" +
    "\001\002\000\004\051\035\001\002\000\062\002\uffe1\004" +
    "\uffe1\005\uffe1\006\uffe1\007\uffe1\010\uffe1\012\uffe1\013\uffe1" +
    "\014\uffe1\015\uffe1\016\uffe1\017\uffe1\020\uffe1\021\uffe1\022" +
    "\uffe1\023\uffe1\030\uffe1\032\063\033\065\034\uffe1\036\uffe1" +
    "\037\uffe1\040\uffe1\041\uffe1\001\002\000\056\002\uffe3\004" +
    "\uffe3\005\uffe3\006\uffe3\007\uffe3\010\uffe3\012\uffe3\013\uffe3" +
    "\014\uffe3\015\uffe3\016\uffe3\017\uffe3\020\uffe3\021\uffe3\022" +
    "\uffe3\023\uffe3\030\uffe3\034\uffe3\036\uffe3\037\uffe3\040\uffe3" +
    "\041\uffe3\001\002\000\064\002\uffc3\004\uffc3\005\uffc3\006" +
    "\uffc3\007\uffc3\010\uffc3\012\uffc3\013\uffc3\014\uffc3\015\uffc3" +
    "\016\uffc3\017\uffc3\020\uffc3\021\uffc3\022\uffc3\023\uffc3\027" +
    "\uffc3\030\uffc3\032\uffc3\033\uffc3\034\uffc3\036\uffc3\037\uffc3" +
    "\040\uffc3\041\uffc3\001\002\000\064\002\uffc1\004\uffc1\005" +
    "\uffc1\006\uffc1\007\uffc1\010\uffc1\012\uffc1\013\uffc1\014\uffc1" +
    "\015\uffc1\016\uffc1\017\uffc1\020\uffc1\021\uffc1\022\uffc1\023" +
    "\uffc1\027\uffc1\030\uffc1\032\uffc1\033\uffc1\034\uffc1\036\uffc1" +
    "\037\uffc1\040\uffc1\041\uffc1\001\002\000\062\002\uffe1\004" +
    "\uffe1\005\uffe1\006\uffe1\007\uffe1\010\uffe1\012\uffe1\013\uffe1" +
    "\014\uffe1\015\uffe1\016\uffe1\017\uffe1\020\uffe1\021\uffe1\022" +
    "\uffe1\023\uffe1\030\uffe1\032\063\033\065\034\uffe1\036\uffe1" +
    "\037\uffe1\040\uffe1\041\uffe1\001\002\000\064\002\uffc0\004" +
    "\uffc0\005\uffc0\006\uffc0\007\uffc0\010\uffc0\012\uffc0\013\uffc0" +
    "\014\uffc0\015\uffc0\016\uffc0\017\uffc0\020\uffc0\021\uffc0\022" +
    "\uffc0\023\uffc0\027\uffc0\030\uffc0\032\uffc0\033\uffc0\034\uffc0" +
    "\036\uffc0\037\uffc0\040\uffc0\041\uffc0\001\002\000\064\002" +
    "\uffbd\004\uffbd\005\uffbd\006\uffbd\007\uffbd\010\uffbd\012\uffbd" +
    "\013\uffbd\014\uffbd\015\uffbd\016\uffbd\017\uffbd\020\uffbd\021" +
    "\uffbd\022\uffbd\023\uffbd\027\uffbd\030\uffbd\032\uffbd\033\uffbd" +
    "\034\uffbd\036\uffbd\037\uffbd\040\uffbd\041\uffbd\001\002\000" +
    "\064\002\uffbf\004\uffbf\005\uffbf\006\uffbf\007\uffbf\010\uffbf" +
    "\012\uffbf\013\uffbf\014\uffbf\015\uffbf\016\uffbf\017\uffbf\020" +
    "\uffbf\021\uffbf\022\uffbf\023\uffbf\027\uffbf\030\uffbf\032\uffbf" +
    "\033\uffbf\034\uffbf\036\uffbf\037\uffbf\040\uffbf\041\uffbf\001" +
    "\002\000\064\002\uffd8\004\uffd8\005\uffd8\006\uffd8\007\uffd8" +
    "\010\uffd8\012\uffd8\013\uffd8\014\uffd8\015\uffd8\016\uffd8\017" +
    "\uffd8\020\uffd8\021\uffd8\022\uffd8\023\uffd8\027\103\030\uffd8" +
    "\032\uffd8\033\uffd8\034\uffd8\036\uffd8\037\uffd8\040\uffd8\041" +
    "\uffd8\001\002\000\064\002\uffbe\004\uffbe\005\uffbe\006\uffbe" +
    "\007\uffbe\010\uffbe\012\uffbe\013\uffbe\014\uffbe\015\uffbe\016" +
    "\uffbe\017\uffbe\020\uffbe\021\uffbe\022\uffbe\023\uffbe\027\uffbe" +
    "\030\uffbe\032\uffbe\033\uffbe\034\uffbe\036\uffbe\037\uffbe\040" +
    "\uffbe\041\uffbe\001\002\000\064\002\uffc2\004\uffc2\005\uffc2" +
    "\006\uffc2\007\uffc2\010\uffc2\012\uffc2\013\uffc2\014\uffc2\015" +
    "\uffc2\016\uffc2\017\uffc2\020\uffc2\021\uffc2\022\uffc2\023\uffc2" +
    "\027\uffc2\030\uffc2\032\uffc2\033\uffc2\034\uffc2\036\uffc2\037" +
    "\uffc2\040\uffc2\041\uffc2\001\002\000\062\002\uffda\004\uffda" +
    "\005\uffda\006\uffda\007\uffda\010\uffda\012\uffda\013\uffda\014" +
    "\uffda\015\uffda\016\uffda\017\uffda\020\uffda\021\uffda\022\uffda" +
    "\023\uffda\030\uffda\032\uffda\033\uffda\034\uffda\036\uffda\037" +
    "\uffda\040\uffda\041\uffda\001\002\000\062\002\uffd9\004\uffd9" +
    "\005\uffd9\006\uffd9\007\uffd9\010\uffd9\012\uffd9\013\uffd9\014" +
    "\uffd9\015\uffd9\016\uffd9\017\uffd9\020\uffd9\021\uffd9\022\uffd9" +
    "\023\uffd9\030\uffd9\032\uffd9\033\uffd9\034\uffd9\036\uffd9\037" +
    "\uffd9\040\uffd9\041\uffd9\001\002\000\026\011\027\021\047" +
    "\027\034\030\104\035\033\051\107\052\041\053\050\054" +
    "\032\055\046\001\002\000\062\002\uffd2\004\uffd2\005\uffd2" +
    "\006\uffd2\007\uffd2\010\uffd2\012\uffd2\013\uffd2\014\uffd2\015" +
    "\uffd2\016\uffd2\017\uffd2\020\uffd2\021\uffd2\022\uffd2\023\uffd2" +
    "\030\uffd2\032\uffd2\033\uffd2\034\uffd2\036\uffd2\037\uffd2\040" +
    "\uffd2\041\uffd2\001\002\000\024\011\027\021\047\027\034" +
    "\035\033\051\035\052\041\053\050\054\032\055\046\001" +
    "\002\000\062\002\uffd7\004\uffd7\005\uffd7\006\uffd7\007\uffd7" +
    "\010\uffd7\012\uffd7\013\uffd7\014\uffd7\015\uffd7\016\uffd7\017" +
    "\uffd7\020\uffd7\021\uffd7\022\uffd7\023\uffd7\030\uffd7\032\uffd7" +
    "\033\uffd7\034\uffd7\036\uffd7\037\uffd7\040\uffd7\041\uffd7\001" +
    "\002\000\060\006\uffc8\007\uffc8\010\uffc8\012\uffc8\013\uffc8" +
    "\014\uffc8\015\uffc8\016\uffc8\017\uffc8\020\uffc8\021\uffc8\022" +
    "\uffc8\023\uffc8\024\uffce\025\uffce\026\114\027\uffc8\030\uffc8" +
    "\031\113\032\uffc8\033\uffc8\034\uffce\041\uffc8\001\002\000" +
    "\004\030\uffd6\001\002\000\004\030\112\001\002\000\062" +
    "\002\uffd5\004\uffd5\005\uffd5\006\uffd5\007\uffd5\010\uffd5\012" +
    "\uffd5\013\uffd5\014\uffd5\015\uffd5\016\uffd5\017\uffd5\020\uffd5" +
    "\021\uffd5\022\uffd5\023\uffd5\030\uffd5\032\uffd5\033\uffd5\034" +
    "\uffd5\036\uffd5\037\uffd5\040\uffd5\041\uffd5\001\002\000\004" +
    "\051\134\001\002\000\004\051\132\001\002\000\064\002" +
    "\uffca\004\uffca\005\uffca\006\uffca\007\uffca\010\uffca\012\uffca" +
    "\013\uffca\014\uffca\015\uffca\016\uffca\017\uffca\020\uffca\021" +
    "\uffca\022\uffca\023\uffca\027\uffca\030\uffca\032\uffca\033\uffca" +
    "\034\uffca\036\uffca\037\uffca\040\uffca\041\uffca\001\002\000" +
    "\010\024\uffd1\025\uffd1\034\uffd1\001\002\000\010\024\120" +
    "\025\121\034\uffcb\001\002\000\004\051\125\001\002\000" +
    "\004\051\124\001\002\000\004\034\123\001\002\000\024" +
    "\011\uffd0\021\uffd0\027\uffd0\035\uffd0\051\uffd0\052\uffd0\053" +
    "\uffd0\054\uffd0\055\uffd0\001\002\000\004\034\uffcc\001\002" +
    "\000\004\025\126\001\002\000\004\051\035\001\002\000" +
    "\004\016\130\001\002\000\024\011\027\021\047\027\034" +
    "\035\033\051\035\052\041\053\050\054\032\055\046\001" +
    "\002\000\004\034\uffcd\001\002\000\066\002\uffc8\004\uffc8" +
    "\005\uffc8\006\uffc8\007\uffc8\010\uffc8\012\uffc8\013\uffc8\014" +
    "\uffc8\015\uffc8\016\uffc8\017\uffc8\020\uffc8\021\uffc8\022\uffc8" +
    "\023\uffc8\026\114\027\uffc8\030\uffc8\032\uffc8\033\uffc8\034" +
    "\uffc8\036\uffc8\037\uffc8\040\uffc8\041\uffc8\001\002\000\064" +
    "\002\uffc9\004\uffc9\005\uffc9\006\uffc9\007\uffc9\010\uffc9\012" +
    "\uffc9\013\uffc9\014\uffc9\015\uffc9\016\uffc9\017\uffc9\020\uffc9" +
    "\021\uffc9\022\uffc9\023\uffc9\027\uffc9\030\uffc9\032\uffc9\033" +
    "\uffc9\034\uffc9\036\uffc9\037\uffc9\040\uffc9\041\uffc9\001\002" +
    "\000\012\024\uffce\025\uffce\031\113\034\uffce\001\002\000" +
    "\010\024\uffcf\025\uffcf\034\uffcf\001\002\000\004\030\uffd4" +
    "\001\002\000\004\030\140\001\002\000\062\002\uffd3\004" +
    "\uffd3\005\uffd3\006\uffd3\007\uffd3\010\uffd3\012\uffd3\013\uffd3" +
    "\014\uffd3\015\uffd3\016\uffd3\017\uffd3\020\uffd3\021\uffd3\022" +
    "\uffd3\023\uffd3\030\uffd3\032\uffd3\033\uffd3\034\uffd3\036\uffd3" +
    "\037\uffd3\040\uffd3\041\uffd3\001\002\000\056\002\uffe2\004" +
    "\uffe2\005\uffe2\006\uffe2\007\uffe2\010\uffe2\012\uffe2\013\uffe2" +
    "\014\uffe2\015\uffe2\016\uffe2\017\uffe2\020\uffe2\021\uffe2\022" +
    "\uffe2\023\uffe2\030\uffe2\034\uffe2\036\uffe2\037\uffe2\040\uffe2" +
    "\041\uffe2\001\002\000\004\030\143\001\002\000\062\002" +
    "\uffde\004\uffde\005\uffde\006\uffde\007\uffde\010\uffde\012\uffde" +
    "\013\uffde\014\uffde\015\uffde\016\uffde\017\uffde\020\uffde\021" +
    "\uffde\022\uffde\023\uffde\030\uffde\032\uffde\033\uffde\034\uffde" +
    "\036\uffde\037\uffde\040\uffde\041\uffde\001\002\000\004\036" +
    "\145\001\002\000\024\011\027\021\047\027\034\035\033" +
    "\051\035\052\041\053\050\054\032\055\046\001\002\000" +
    "\004\037\147\001\002\000\024\011\027\021\047\027\034" +
    "\035\033\051\035\052\041\053\050\054\032\055\046\001" +
    "\002\000\004\040\151\001\002\000\062\002\uffdc\004\uffdc" +
    "\005\uffdc\006\uffdc\007\uffdc\010\uffdc\012\uffdc\013\uffdc\014" +
    "\uffdc\015\uffdc\016\uffdc\017\uffdc\020\uffdc\021\uffdc\022\uffdc" +
    "\023\uffdc\030\uffdc\032\uffdc\033\uffdc\034\uffdc\036\uffdc\037" +
    "\uffdc\040\uffdc\041\uffdc\001\002\000\024\011\uffba\021\uffba" +
    "\027\uffba\035\uffba\051\uffba\052\uffba\053\uffba\054\uffba\055" +
    "\uffba\001\002\000\024\011\027\021\047\027\034\035\033" +
    "\051\035\052\041\053\050\054\032\055\046\001\002\000" +
    "\024\011\uffb9\021\uffb9\027\uffb9\035\uffb9\051\uffb9\052\uffb9" +
    "\053\uffb9\054\uffb9\055\uffb9\001\002\000\052\002\uffe9\004" +
    "\uffe9\005\uffe9\006\uffe9\007\uffe9\010\uffe9\012\uffe9\013\uffe9" +
    "\014\uffe9\015\uffe9\016\uffe9\017\uffe9\020\uffe9\021\uffe9\030" +
    "\uffe9\034\uffe9\036\uffe9\037\uffe9\040\uffe9\041\uffe9\001\002" +
    "\000\056\002\uffe7\004\uffe7\005\uffe7\006\uffe7\007\uffe7\010" +
    "\uffe7\012\uffe7\013\uffe7\014\uffe7\015\uffe7\016\uffe7\017\uffe7" +
    "\020\uffe7\021\uffe7\022\152\023\154\030\uffe7\034\uffe7\036" +
    "\uffe7\037\uffe7\040\uffe7\041\uffe7\001\002\000\052\002\uffe8" +
    "\004\uffe8\005\uffe8\006\uffe8\007\uffe8\010\uffe8\012\uffe8\013" +
    "\uffe8\014\uffe8\015\uffe8\016\uffe8\017\uffe8\020\uffe8\021\uffe8" +
    "\030\uffe8\034\uffe8\036\uffe8\037\uffe8\040\uffe8\041\uffe8\001" +
    "\002\000\062\002\uffdb\004\uffdb\005\uffdb\006\uffdb\007\uffdb" +
    "\010\uffdb\012\uffdb\013\uffdb\014\uffdb\015\uffdb\016\uffdb\017" +
    "\uffdb\020\uffdb\021\uffdb\022\uffdb\023\uffdb\030\uffdb\032\uffdb" +
    "\033\uffdb\034\uffdb\036\uffdb\037\uffdb\040\uffdb\041\uffdb\001" +
    "\002\000\024\011\uffb0\021\uffb0\027\uffb0\035\uffb0\051\uffb0" +
    "\052\uffb0\053\uffb0\054\uffb0\055\uffb0\001\002\000\024\011" +
    "\027\021\047\027\034\035\033\051\035\052\041\053\050" +
    "\054\032\055\046\001\002\000\024\011\uffb1\021\uffb1\027" +
    "\uffb1\035\uffb1\051\uffb1\052\uffb1\053\uffb1\054\uffb1\055\uffb1" +
    "\001\002\000\024\011\uffb2\021\uffb2\027\uffb2\035\uffb2\051" +
    "\uffb2\052\uffb2\053\uffb2\054\uffb2\055\uffb2\001\002\000\024" +
    "\011\uffae\021\uffae\027\uffae\035\uffae\051\uffae\052\uffae\053" +
    "\uffae\054\uffae\055\uffae\001\002\000\024\011\uffad\021\uffad" +
    "\027\uffad\035\uffad\051\uffad\052\uffad\053\uffad\054\uffad\055" +
    "\uffad\001\002\000\024\011\uffaf\021\uffaf\027\uffaf\035\uffaf" +
    "\051\uffaf\052\uffaf\053\uffaf\054\uffaf\055\uffaf\001\002\000" +
    "\032\002\uffef\004\uffef\005\uffef\006\uffef\007\uffef\010\uffef" +
    "\030\uffef\034\uffef\036\uffef\037\uffef\040\uffef\041\uffef\001" +
    "\002\000\032\002\uffee\004\uffee\005\uffee\006\uffee\007\uffee" +
    "\010\uffee\030\uffee\034\uffee\036\uffee\037\uffee\040\uffee\041" +
    "\uffee\001\002\000\056\002\uffe6\004\uffe6\005\uffe6\006\uffe6" +
    "\007\uffe6\010\uffe6\012\uffe6\013\uffe6\014\uffe6\015\uffe6\016" +
    "\uffe6\017\uffe6\020\uffe6\021\uffe6\022\uffe6\023\uffe6\030\uffe6" +
    "\034\uffe6\036\uffe6\037\uffe6\040\uffe6\041\uffe6\001\002\000" +
    "\046\002\uffec\004\uffec\005\uffec\006\uffec\007\uffec\010\uffec" +
    "\012\uffec\013\uffec\014\uffec\015\uffec\016\uffec\017\uffec\030" +
    "\uffec\034\uffec\036\uffec\037\uffec\040\uffec\041\uffec\001\002" +
    "\000\024\011\uffbc\021\uffbc\027\uffbc\035\uffbc\051\uffbc\052" +
    "\uffbc\053\uffbc\054\uffbc\055\uffbc\001\002\000\024\011\uffbb" +
    "\021\uffbb\027\uffbb\035\uffbb\051\uffbb\052\uffbb\053\uffbb\054" +
    "\uffbb\055\uffbb\001\002\000\024\011\027\021\047\027\034" +
    "\035\033\051\035\052\041\053\050\054\032\055\046\001" +
    "\002\000\052\002\uffea\004\uffea\005\uffea\006\uffea\007\uffea" +
    "\010\uffea\012\uffea\013\uffea\014\uffea\015\uffea\016\uffea\017" +
    "\uffea\020\174\021\175\030\uffea\034\uffea\036\uffea\037\uffea" +
    "\040\uffea\041\uffea\001\002\000\046\002\uffeb\004\uffeb\005" +
    "\uffeb\006\uffeb\007\uffeb\010\uffeb\012\uffeb\013\uffeb\014\uffeb" +
    "\015\uffeb\016\uffeb\017\uffeb\030\uffeb\034\uffeb\036\uffeb\037" +
    "\uffeb\040\uffeb\041\uffeb\001\002\000\024\011\027\021\047" +
    "\027\034\035\033\051\035\052\041\053\050\054\032\055" +
    "\046\001\002\000\010\002\ufff6\004\ufff6\005\ufff6\001\002" +
    "\000\010\002\ufff4\004\ufff4\005\021\001\002\000\006\002" +
    "\ufff5\004\ufff5\001\002\000\004\002\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\203\000\010\002\003\004\005\005\004\001\001\000" +
    "\002\001\001\000\004\011\017\001\001\000\004\046\015" +
    "\001\001\000\004\006\007\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\002\016\004\005\005" +
    "\004\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\034\007\044\010\036\012" +
    "\050\013\042\014\041\015\025\016\023\017\030\020\037" +
    "\026\043\027\024\034\035\035\027\001\001\000\006\021" +
    "\172\030\175\001\001\000\016\010\036\012\050\020\171" +
    "\026\043\034\035\035\027\001\001\000\006\025\167\032" +
    "\161\001\001\000\002\001\001\000\006\037\101\041\157" +
    "\001\001\000\006\022\154\031\152\001\001\000\002\001" +
    "\001\000\034\007\143\010\036\012\050\013\042\014\041" +
    "\015\025\016\023\017\030\020\037\026\043\027\024\034" +
    "\035\035\027\001\001\000\034\007\141\010\036\012\050" +
    "\013\042\014\041\015\025\016\023\017\030\020\037\026" +
    "\043\027\024\034\035\035\027\001\001\000\004\036\114" +
    "\001\001\000\002\001\001\000\004\023\063\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\024\055\033\053" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\047" +
    "\051\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\011\052\001\001\000" +
    "\002\001\001\000\032\010\036\012\050\013\061\014\041" +
    "\015\025\016\023\017\030\020\037\026\043\027\024\034" +
    "\035\035\027\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\044\075\045\071\001\001\000\002" +
    "\001\001\000\006\034\065\035\027\001\001\000\004\023" +
    "\066\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\023\140\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\037\101\041\100" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\040\007\107\010\036\012\050" +
    "\013\042\014\041\015\025\016\023\017\030\020\037\026" +
    "\043\027\024\034\035\035\027\040\105\042\104\001\001" +
    "\000\002\001\001\000\034\007\135\010\036\012\050\013" +
    "\042\014\041\015\025\016\023\017\030\020\037\026\043" +
    "\027\024\034\035\035\027\001\001\000\002\001\001\000" +
    "\006\036\114\043\115\001\001\000\004\051\110\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\053\116\001\001" +
    "\000\004\003\121\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\035\126\001\001\000\002\001" +
    "\001\000\034\007\130\010\036\012\050\013\042\014\041" +
    "\015\025\016\023\017\030\020\037\026\043\027\024\034" +
    "\035\035\027\001\001\000\002\001\001\000\004\036\132" +
    "\001\001\000\002\001\001\000\004\043\134\001\001\000" +
    "\002\001\001\000\004\052\136\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\034\007\145\010\036" +
    "\012\050\013\042\014\041\015\025\016\023\017\030\020" +
    "\037\026\043\027\024\034\035\035\027\001\001\000\002" +
    "\001\001\000\034\007\147\010\036\012\050\013\042\014" +
    "\041\015\025\016\023\017\030\020\037\026\043\027\024" +
    "\034\035\035\027\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\010\036\012\050\017\155" +
    "\020\037\026\043\027\024\034\035\035\027\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\022\156\031\152" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\026\010\036\012\050\015\170\016\023\017\030" +
    "\020\037\026\043\027\024\034\035\035\027\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\024\010\036\012\050\016\176\017" +
    "\030\020\037\026\043\027\024\034\035\035\027\001\001" +
    "\000\006\021\177\030\175\001\001\000\002\001\001\000" +
    "\034\007\201\010\036\012\050\013\042\014\041\015\025" +
    "\016\023\017\030\020\037\026\043\027\024\034\035\035" +
    "\027\001\001\000\004\050\202\001\001\000\004\011\203" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$OclCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$OclCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$OclCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 2;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    GeradorDeCodigo ger = GeradorDeCodigo.getInstance();

    public void report_error(String message, Object info) {
   
        StringBuffer m = new StringBuffer("Error");
   
        if (info instanceof java_cup.runtime.Symbol) {
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
            if (s.left >= 0) {
                /* Add to the end of the StringBuffer error message
                   the line number of the error in the input. */
                m.append(" in line "+(s.left+1));   
                /* Check if the column number in the input is greater
                   or equal to zero. */
                if (s.right >= 0)                    
                    /* Add to the end of the StringBuffer error message
                       the column number of the error in the input. */
                    m.append(", column "+(s.right+1));
            }
        }
   
        m.append(" : "+message);
        System.err.println(m);
    }

    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$OclCup$actions {
  private final OclCup parser;

  /** Constructor */
  CUP$OclCup$actions(OclCup parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$OclCup$do_action(
    int                        CUP$OclCup$act_num,
    java_cup.runtime.lr_parser CUP$OclCup$parser,
    java.util.Stack            CUP$OclCup$stack,
    int                        CUP$OclCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$OclCup$result;

      /* select the action based on the action number */
      switch (CUP$OclCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // OperadorRelacional ::= NEQUAL 
            {
              Operador RESULT =null;
		RESULT = new Operador(Operador.DIF);
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorRelacional",24, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // OperadorRelacional ::= LE 
            {
              Operador RESULT =null;
		RESULT = new Operador(Operador.MENORIGUAL);
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorRelacional",24, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // OperadorRelacional ::= GE 
            {
              Operador RESULT =null;
		RESULT = new Operador(Operador.MAIORIGUAL);
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorRelacional",24, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // OperadorRelacional ::= LT 
            {
              Operador RESULT =null;
		RESULT = new Operador(Operador.MENORQ);
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorRelacional",24, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // OperadorRelacional ::= GT 
            {
              Operador RESULT =null;
		RESULT = new Operador(Operador.MAIORQ);
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorRelacional",24, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // OperadorRelacional ::= EQUAL 
            {
              Operador RESULT =null;
		RESULT = new Operador(Operador.IGUAL);
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorRelacional",24, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // OperadorLogico ::= IMPLIES 
            {
              Operador RESULT =null;
		 RESULT = new Operador(Operador.IMPLIES);
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorLogico",25, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // OperadorLogico ::= XOR 
            {
              Operador RESULT =null;
		RESULT = new Operador(Operador.XOR);
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorLogico",25, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // OperadorLogico ::= OR 
            {
              Operador RESULT =null;
		RESULT = new Operador(Operador.OR);
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorLogico",25, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // OperadorLogico ::= AND 
            {
              Operador RESULT =null;
		RESULT = new Operador(Operador.AND);
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorLogico",25, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // OperadorUnario ::= NOT 
            {
              Operador RESULT =null;
		RESULT = new Operador(Operador.NOT);
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorUnario",21, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // OperadorUnario ::= MINUS 
            {
              Operador RESULT =null;
		RESULT = new Operador(Operador.MENOSU);
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorUnario",21, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // OperadorMulti ::= DIVIDE 
            {
              Operador RESULT =null;
		RESULT = new Operador(Operador.DIVIDIDO);
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorMulti",23, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // OperadorMulti ::= MULT 
            {
              Operador RESULT =null;
		RESULT = new Operador(Operador.VEZES);
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorMulti",23, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // OperadorMais ::= MINUS 
            {
              Operador RESULT =null;
		RESULT = new Operador(Operador.MENOS);
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorMais",22, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // OperadorMais ::= PLUS 
            {
              Operador RESULT =null;
		 RESULT = new Operador(Operador.MAIS);
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorMais",22, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // OperadorColecao ::= FORALL 
            {
              OprdCol RESULT =null;
		 RESULT = new OprdCol(OprdCol.FORALL); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorColecao",34, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // OperadorColecao ::= SELECT 
            {
              OprdCol RESULT =null;
		 RESULT = new OprdCol(OprdCol.SELECT); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorColecao",34, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // OperadorColecao ::= EXISTS 
            {
              OprdCol RESULT =null;
		 RESULT = new OprdCol(OprdCol.EXISTS); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorColecao",34, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // OperadorColecao ::= EXCLUDES 
            {
              OprdCol RESULT =null;
		 RESULT = new OprdCol(OprdCol.EXCLUDES); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorColecao",34, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // OperadorColecao ::= INCLUDES 
            {
              OprdCol RESULT =null;
		 RESULT = new OprdCol(OprdCol.INCLUDES); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorColecao",34, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // OperadorColecao ::= SIZE 
            {
              OprdCol RESULT =null;
		 RESULT = new OprdCol(OprdCol.SIZE); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorColecao",34, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // OperadorColecao ::= INCLUDESALL 
            {
              OprdCol RESULT =null;
		 RESULT = new OprdCol(OprdCol.INCLUDESALL); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("OperadorColecao",34, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // Literal ::= FALSE 
            {
              Literal RESULT =null;
		 RESULT = new Literal("false", Literal.BOOLEANO); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("Literal",8, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // Literal ::= TRUE 
            {
              Literal RESULT =null;
		 RESULT = new Literal("true", Literal.BOOLEANO); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("Literal",8, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // Literal ::= NUMERO 
            {
              Literal RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Literal(n, Literal.NUMERO); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("Literal",8, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // Literal ::= STRING 
            {
              Literal RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Literal(s, Literal.STRING); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("Literal",8, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // CaminhoAux ::= 
            {
              Caminho RESULT =null;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("CaminhoAux",28, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // CaminhoAux ::= DCOLON ID CaminhoAux 
            {
              Caminho RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Caminho c = (Caminho)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Caminho(id, c); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("CaminhoAux",28, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // Caminho ::= ID CaminhoAux 
            {
              Caminho RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Caminho c = (Caminho)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Caminho(id, c); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("Caminho",27, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // EspecificadorTipoOpt ::= 
            {
              No RESULT =null;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("EspecificadorTipoOpt",1, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // EspecificadorTipoOpt ::= COLON ID 
            {
              No RESULT =null;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("EspecificadorTipoOpt",1, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // EspecificadorTipoOpt ::= SEMICOL ID COLON Caminho EQUAL ExpOcl 
            {
              No RESULT =null;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("EspecificadorTipoOpt",1, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-5)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // DeclaradorAux ::= 
            {
              Declarador RESULT =null;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("DeclaradorAux",33, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // DeclaradorAux ::= COMMA ID DeclaradorAux 
            {
              Declarador RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int auxleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int auxright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Declarador aux = (Declarador)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Declarador(id, aux); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("DeclaradorAux",33, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // Declarador ::= ID DeclaradorAux NT$5 EspecificadorTipoOpt BAR 
            {
              Declarador RESULT =null;
              // propagate RESULT from NT$5
                RESULT = (Declarador) ((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-4)).value;
		int auxleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-3)).left;
		int auxright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-3)).right;
		Declarador aux = (Declarador)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-3)).value;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("Declarador",32, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-4)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // NT$5 ::= 
            {
              Declarador RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int auxleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int auxright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Declarador aux = (Declarador)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
 RESULT = new Declarador(id, aux); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("NT$5",41, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // ParametrosChamadaPropriedadeAux ::= RPAREN 
            {
              Parametros RESULT =null;
		 RESULT = new Parametros(); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ParametrosChamadaPropriedadeAux",30, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // ParametrosChamadaPropriedadeAux ::= Declarador ExpOcl NT$4 RPAREN 
            {
              Parametros RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (Parametros) ((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-3)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-3)).right;
		Declarador d = (Declarador)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).right;
		Expressao e = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).value;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ParametrosChamadaPropriedadeAux",30, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-3)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // NT$4 ::= 
            {
              Parametros RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		Declarador d = (Declarador)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao e = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
 RESULT = new Parametros(d, e); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("NT$4",40, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // ParametrosChamadaPropriedadeAux ::= ExpOcl NT$3 RPAREN 
            {
              Parametros RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Parametros) ((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).right;
		Expressao e = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).value;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ParametrosChamadaPropriedadeAux",30, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // NT$3 ::= 
            {
              Parametros RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao e = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
 RESULT = new Parametros(e); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("NT$3",39, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // ParametrosChamadaPropriedade ::= LPAREN ParametrosChamadaPropriedadeAux 
            {
              Parametros RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Parametros p = (Parametros)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = p; 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ParametrosChamadaPropriedade",29, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // ParametrosChamadaPropriedadeOpt ::= 
            {
              Parametros RESULT =null;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ParametrosChamadaPropriedadeOpt",31, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // ParametrosChamadaPropriedadeOpt ::= ParametrosChamadaPropriedade 
            {
              Parametros RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Parametros p = (Parametros)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = p; 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ParametrosChamadaPropriedadeOpt",31, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // ChamadaPropriedadeColecao ::= OperadorColecao ParametrosChamadaPropriedadeOpt 
            {
              OperacaoCol RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		OprdCol o = (OprdCol)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Parametros p = (Parametros)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new OperacaoCol(o, p); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ChamadaPropriedadeColecao",35, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // ChamadaPropriedade ::= Caminho ParametrosChamadaPropriedadeOpt 
            {
              Propriedade RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		Caminho c = (Caminho)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Parametros p = (Parametros)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Propriedade(c, p); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ChamadaPropriedade",26, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // ExpressaoIf ::= IF ExpOcl THEN ExpOcl ELSE ExpOcl ENDIF 
            {
              ExpressaoIf RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-5)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-5)).right;
		Expressao e1 = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-5)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-3)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-3)).right;
		Expressao e2 = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-3)).value;
		int e3left = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int e3right = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		Expressao e3 = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		 RESULT = new ExpressaoIf(e1,e2,e3); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpressaoIf",20, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-6)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // ExpPrimaria ::= ExpressaoIf 
            {
              Expressao RESULT =null;
		int eifleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int eifright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		ExpressaoIf eif = (ExpressaoIf)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Expressao(eif); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpPrimaria",6, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // ExpPrimaria ::= LPAREN ExpOcl RPAREN 
            {
              Expressao RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		Expressao e = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		 RESULT = new Expressao(e); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpPrimaria",6, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // ExpPrimaria ::= ChamadaPropriedade 
            {
              Expressao RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Propriedade c = (Propriedade)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Expressao(c); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpPrimaria",6, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // ExpPrimaria ::= Literal 
            {
              Expressao RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Literal l = (Literal)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Expressao(l); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpPrimaria",6, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // ExpPosFixadaAux ::= 
            {
              Expressao RESULT =null;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpPosFixadaAux",17, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // ExpPosFixadaAux ::= RARROW ChamadaPropriedadeColecao ExpPosFixadaAux 
            {
              Expressao RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		OperacaoCol c = (OperacaoCol)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int epfleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int epfright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao epf = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Expressao(c, epf); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpPosFixadaAux",17, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // ExpPosFixadaAux ::= DOT ChamadaPropriedade ExpPosFixadaAux 
            {
              Expressao RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		Propriedade c = (Propriedade)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int epfleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int epfright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao epf = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Expressao(c, epf); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpPosFixadaAux",17, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // ExpPosFixada ::= ExpPrimaria ExpPosFixadaAux 
            {
              Expressao RESULT =null;
		int epleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int epright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		Expressao ep = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int epfleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int epfright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao epf = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Expressao(ep, epf); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpPosFixada",14, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // ExpUnaria ::= ExpPosFixada 
            {
              Expressao RESULT =null;
		int epfleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int epfright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao epf = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Expressao(epf); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpUnaria",13, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // ExpUnaria ::= OperadorUnario ExpPosFixada 
            {
              Expressao RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		Operador o = (Operador)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int epfleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int epfright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao epf = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Expressao(o, epf); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpUnaria",13, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // ExpMultiAux ::= 
            {
              Expressao RESULT =null;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpMultiAux",16, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // ExpMultiAux ::= OperadorMulti ExpUnaria ExpMultiAux 
            {
              Expressao RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).right;
		Operador o = (Operador)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).value;
		int e1left = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		Expressao e1 = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao e2 = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Expressao(o, e1, e2); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpMultiAux",16, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // ExpMultiplicativa ::= ExpUnaria ExpMultiAux 
            {
              Expressao RESULT =null;
		int eunleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int eunright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		Expressao eun = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int eauxleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int eauxright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao eaux = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Expressao(eun, eaux); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpMultiplicativa",12, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // ExpAditivaAux ::= 
            {
              Expressao RESULT =null;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpAditivaAux",15, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // ExpAditivaAux ::= OperadorMais ExpMultiplicativa ExpAditivaAux 
            {
              Expressao RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).right;
		Operador o = (Operador)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).value;
		int op1left = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int op1right = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		Expressao op1 = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int op2left = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int op2right = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao op2 = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Expressao(o, op1, op2);
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpAditivaAux",15, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // ExpAditiva ::= ExpMultiplicativa ExpAditivaAux 
            {
              Expressao RESULT =null;
		int emulleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int emulright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		Expressao emul = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int eauxleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int eauxright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao eaux = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Expressao(emul, eaux); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpAditiva",11, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // ExpRelacionalAux ::= 
            {
              Expressao RESULT =null;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpRelacionalAux",19, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // ExpRelacionalAux ::= OperadorRelacional ExpAditiva 
            {
              Expressao RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		Operador o = (Operador)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao a = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Expressao(o, a); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpRelacionalAux",19, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // ExpRelacional ::= ExpAditiva ExpRelacionalAux 
            {
              Expressao RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		Expressao a = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao e = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Expressao(a, e); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpRelacional",10, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // ExpLogicaAux ::= 
            {
              Expressao RESULT =null;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpLogicaAux",18, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // ExpLogicaAux ::= OperadorLogico ExpLogica 
            {
              Expressao RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		Operador o = (Operador)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao l = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Expressao(o, l); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpLogicaAux",18, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // ExpLogica ::= ExpRelacional ExpLogicaAux 
            {
              Expressao RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		Expressao r = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao e = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Expressao(r, e); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpLogica",9, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // ExpOcl ::= ExpLogica 
            {
              Expressao RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao e = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Expressao(e); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpOcl",5, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // InvContext ::= 
            {
              Invariante RESULT =null;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("InvContext",7, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // InvContext ::= INV ID COLON ExpOcl NT$2 InvContext 
            {
              Invariante RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Invariante) ((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-4)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).right;
		Expressao e = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).value;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("InvContext",7, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-5)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // NT$2 ::= 
            {
              Invariante RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao e = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
 RESULT = new Invariante(e, id); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("NT$2",38, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // InvContext ::= INV COLON ExpOcl NT$1 InvContext 
            {
              Invariante RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Invariante) ((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).right;
		Expressao e = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).value;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("InvContext",7, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-4)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // NT$1 ::= 
            {
              Invariante RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Expressao e = (Expressao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
 RESULT = new Invariante(e); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("NT$1",37, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // ClassifierContexto ::= ID DCOLON ID 
            {
              Classe RESULT =null;
		int id1left = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).left;
		int id1right = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).right;
		String id1 = (String)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).value;
		int id2left = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int id2right = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		String id2 = (String)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Classe(id1, id2); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ClassifierContexto",4, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // ClassifierContexto ::= ID COLON ID 
            {
              Classe RESULT =null;
		int id1left = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).left;
		int id1right = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).right;
		String id1 = (String)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).value;
		int id2left = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int id2right = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		String id2 = (String)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Classe(id1, id2); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ClassifierContexto",4, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // ClassifierContexto ::= ID 
            {
              Classe RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Classe(id); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ClassifierContexto",4, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // DeclaracaoContexto ::= CONTEXT ClassifierContexto 
            {
              Classe RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Classe c = (Classe)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = c;
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("DeclaracaoContexto",3, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Restricao ::= DeclaracaoContexto InvContext 
            {
              Restricao RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		Classe c = (Classe)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Invariante i = (Invariante)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
		 RESULT = new Restricao(c); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("Restricao",2, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // ExpressoesOcl ::= 
            {
              No RESULT =null;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpressoesOcl",0, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // $START ::= ExpressoesOcl EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).right;
		No start_val = (No)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		RESULT = start_val;
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$OclCup$parser.done_parsing();
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // ExpressoesOcl ::= Restricao NT$0 ExpressoesOcl 
            {
              No RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (No) ((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-1)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).right;
		Restricao r = (Restricao)((java_cup.runtime.Symbol) CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)).value;

              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("ExpressoesOcl",0, ((java_cup.runtime.Symbol)CUP$OclCup$stack.elementAt(CUP$OclCup$top-2)), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // NT$0 ::= 
            {
              No RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()).right;
		Restricao r = (Restricao)((java_cup.runtime.Symbol) CUP$OclCup$stack.peek()).value;
 parser.ger.gerarArquivoRuby(r); 
              CUP$OclCup$result = parser.getSymbolFactory().newSymbol("NT$0",36, ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$OclCup$stack.peek()), RESULT);
            }
          return CUP$OclCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

