#!/bin/bash

#Script para compilar arquivos no diretorio correto com nomes padronizados

jflex -d ../src/compil/inv/parser/ ocl.lex
cup -parser OCLParser -symbols OCLSym -destdir ../src/compil/inv/parser/ ocl.cup 

