#!/bin/bash

#Script para compilar arquivos no diretorio correto com nomes padronizados

jflex -d ../compil/inv/parser/ ocl.lex
cup -parser OCL_Parser -symbols OCL_Sym -destdir ../compil/inv/parser/ ocl.cup 

