/* The following code was generated by JFlex 1.4.3 on 28/03/11 03:42 */

package compil.inv.parser;

import java_cup.runtime.*;
import java.io.IOException;

import compil.inv.parser.OclSym;
import static compil.inv.parser.OclSym.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 28/03/11 03:42 from the specification file
 * <tt>/home/vladymir/java_workspace/OclRubyCompiler/gramatica/ocl.lex</tt>
 */
public class OCL_Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\37\1\2\1\0\1\37\1\1\22\0\1\40\1\0\1\35"+
    "\1\0\4\0\1\3\1\4\1\14\1\13\1\6\1\12\1\0\1\15"+
    "\12\17\1\5\1\0\1\10\1\7\1\11\1\0\1\0\1\46\1\30"+
    "\6\16\1\26\4\16\1\51\3\16\1\34\1\20\7\16\1\0\1\0"+
    "\1\0\3\0\1\33\1\16\1\41\1\50\1\27\1\45\1\25\1\54"+
    "\1\23\2\16\1\32\1\55\1\24\1\31\1\56\1\16\1\22\1\44"+
    "\1\21\1\47\1\43\1\52\1\42\1\16\1\53\1\0\1\0\1\0"+
    "\1\36\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\10\15"+
    "\1\0\1\1\3\15\1\17\1\20\1\21\1\22\6\17"+
    "\1\23\16\17\1\15\1\16\4\15\1\24\11\15\1\25"+
    "\1\0\2\15\1\26\4\15\1\27\1\30\4\15\1\31"+
    "\4\15\1\32\1\15\1\33\1\15\1\34\6\15\1\35"+
    "\7\15\1\36\3\15\1\37\4\15\1\40\1\41\1\15"+
    "\1\42\2\15\1\43\2\15\1\44\1\45\1\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\57\0\57\0\57\0\57"+
    "\0\57\0\274\0\353\0\57\0\57\0\57\0\57\0\u011a"+
    "\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292"+
    "\0\u02c1\0\u02f0\0\57\0\u031f\0\u034e\0\u037d\0\215\0\215"+
    "\0\215\0\215\0\u03ac\0\u03db\0\u040a\0\u0439\0\u0468\0\u0497"+
    "\0\u03ac\0\u04c6\0\u04f5\0\u0524\0\u0553\0\u0582\0\u05b1\0\u05e0"+
    "\0\u060f\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa\0\u0729\0\u03ac"+
    "\0\u03db\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u03ac\0\u0814\0\u0843"+
    "\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u098c\0\215"+
    "\0\u063e\0\u09bb\0\u09ea\0\u03ac\0\u0a19\0\u0a48\0\u0a77\0\u0aa6"+
    "\0\u03ac\0\u03ac\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\u03ac\0\u0b91"+
    "\0\u0bc0\0\u0bef\0\u0c1e\0\u03ac\0\u0c4d\0\u03ac\0\u0c7c\0\u03ac"+
    "\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67\0\u0d96\0\u03ac\0\u0dc5"+
    "\0\u0df4\0\u0e23\0\u0e52\0\u0e81\0\u0eb0\0\u0edf\0\u03ac\0\u0f0e"+
    "\0\u0f3d\0\u0f6c\0\u03ac\0\u0f9b\0\u0fca\0\u0ff9\0\u1028\0\u03ac"+
    "\0\u03ac\0\u1057\0\u03ac\0\u1086\0\u10b5\0\u03ac\0\u10e4\0\u1113"+
    "\0\u03ac\0\u03ac\0\u03ac";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\20\1\24\2\20\1\25\1\26\1\27"+
    "\1\30\2\20\1\31\1\32\1\2\2\33\1\34\2\20"+
    "\1\35\1\36\11\20\2\37\1\0\56\37\1\4\54\37"+
    "\57\0\2\37\1\0\4\37\1\40\1\37\1\41\47\37"+
    "\1\0\4\37\1\42\51\37\1\0\13\37\17\43\4\37"+
    "\16\43\2\37\1\0\14\37\1\44\41\37\1\0\13\37"+
    "\3\43\1\45\13\43\4\37\16\43\2\37\1\0\13\37"+
    "\4\43\1\46\12\43\4\37\13\43\1\47\2\43\2\37"+
    "\1\0\13\37\6\43\1\50\10\43\4\37\4\43\1\51"+
    "\7\43\1\52\1\43\2\37\1\0\13\37\6\43\1\53"+
    "\10\43\4\37\16\43\2\37\1\0\13\37\6\43\1\54"+
    "\5\43\1\55\2\43\4\37\1\43\1\56\14\43\2\37"+
    "\1\0\13\37\13\43\1\57\3\43\4\37\16\43\2\37"+
    "\1\0\13\37\17\43\4\37\1\60\15\43\2\37\1\0"+
    "\13\37\11\43\1\61\5\43\4\37\16\43\2\37\1\0"+
    "\33\37\1\62\1\37\1\62\20\37\1\0\13\37\13\43"+
    "\1\63\3\43\4\37\16\43\2\37\1\0\13\37\5\43"+
    "\1\64\3\43\1\65\5\43\4\37\16\43\2\37\1\0"+
    "\13\37\13\43\1\66\1\43\1\67\1\43\4\37\16\43"+
    "\16\0\17\70\4\0\16\70\17\0\1\71\55\0\4\70"+
    "\1\72\12\70\4\0\16\70\16\0\17\70\4\0\6\70"+
    "\1\73\7\70\16\0\11\70\1\74\5\70\4\0\16\70"+
    "\16\0\17\70\4\0\1\75\1\70\1\76\13\70\16\0"+
    "\17\70\4\0\15\70\1\77\16\0\3\70\1\100\13\70"+
    "\4\0\16\70\16\0\17\70\4\0\7\70\1\101\6\70"+
    "\16\0\17\70\4\0\3\70\1\102\12\70\16\0\5\70"+
    "\1\103\11\70\4\0\1\104\15\70\16\0\13\70\1\105"+
    "\3\70\4\0\16\70\16\0\14\70\1\106\2\70\4\0"+
    "\16\70\16\0\15\70\1\107\1\70\4\0\16\70\35\0"+
    "\1\110\1\111\1\0\1\111\34\0\6\70\1\112\10\70"+
    "\4\0\16\70\16\0\17\70\4\0\12\70\1\113\3\70"+
    "\16\0\3\70\1\114\10\70\1\115\2\70\4\0\16\70"+
    "\16\0\4\70\1\116\12\70\4\0\16\70\16\0\14\70"+
    "\1\117\2\70\4\0\16\70\16\0\5\70\1\120\11\70"+
    "\4\0\16\70\16\0\11\70\1\121\5\70\4\0\16\70"+
    "\16\0\6\70\1\122\10\70\4\0\16\70\16\0\14\70"+
    "\1\123\2\70\4\0\16\70\16\0\14\70\1\124\2\70"+
    "\4\0\16\70\16\0\11\70\1\125\5\70\4\0\16\70"+
    "\16\0\5\70\1\126\11\70\4\0\16\70\16\0\11\70"+
    "\1\127\5\70\4\0\16\70\16\0\17\70\4\0\3\70"+
    "\1\130\12\70\16\0\14\70\1\131\2\70\4\0\16\70"+
    "\16\0\14\70\1\132\2\70\4\0\16\70\16\0\10\70"+
    "\1\133\6\70\4\0\16\70\16\0\14\70\1\134\2\70"+
    "\4\0\16\70\16\0\3\70\1\135\13\70\4\0\16\70"+
    "\16\0\11\70\1\136\5\70\4\0\16\70\16\0\11\70"+
    "\1\137\5\70\4\0\4\70\1\140\11\70\16\0\17\70"+
    "\4\0\5\70\1\141\10\70\16\0\17\70\4\0\3\70"+
    "\1\142\12\70\16\0\6\70\1\143\10\70\4\0\16\70"+
    "\16\0\17\70\4\0\6\70\1\144\7\70\16\0\5\70"+
    "\1\145\11\70\4\0\16\70\16\0\7\70\1\146\7\70"+
    "\4\0\16\70\16\0\17\70\4\0\4\70\1\147\11\70"+
    "\16\0\3\70\1\150\13\70\4\0\16\70\16\0\17\70"+
    "\4\0\6\70\1\151\7\70\16\0\11\70\1\152\5\70"+
    "\4\0\16\70\16\0\17\70\4\0\3\70\1\153\12\70"+
    "\16\0\11\70\1\154\5\70\4\0\16\70\16\0\17\70"+
    "\4\0\1\155\15\70\16\0\14\70\1\156\2\70\4\0"+
    "\16\70\16\0\11\70\1\157\5\70\4\0\16\70\16\0"+
    "\7\70\1\134\7\70\4\0\16\70\16\0\17\70\4\0"+
    "\7\70\1\160\6\70\16\0\11\70\1\161\5\70\4\0"+
    "\16\70\16\0\11\70\1\162\5\70\4\0\16\70\16\0"+
    "\17\70\4\0\3\70\1\163\12\70\16\0\17\70\4\0"+
    "\7\70\1\164\6\70\16\0\15\70\1\165\1\70\4\0"+
    "\16\70\16\0\17\70\4\0\10\70\1\166\5\70\16\0"+
    "\17\70\4\0\1\70\1\167\14\70\16\0\3\70\1\170"+
    "\13\70\4\0\16\70\16\0\14\70\1\171\2\70\4\0"+
    "\16\70\16\0\5\70\1\172\11\70\4\0\16\70\16\0"+
    "\17\70\4\0\3\70\1\173\12\70\16\0\4\70\1\134"+
    "\12\70\4\0\16\70\16\0\5\70\1\174\11\70\4\0"+
    "\16\70\16\0\6\70\1\134\10\70\4\0\16\70\16\0"+
    "\11\70\1\175\5\70\4\0\16\70\16\0\3\70\1\176"+
    "\13\70\4\0\16\70\16\0\6\70\1\177\10\70\4\0"+
    "\16\70\16\0\6\70\1\200\10\70\4\0\16\70\16\0"+
    "\17\70\4\0\11\70\1\201\4\70\16\0\7\70\1\202"+
    "\7\70\4\0\16\70\16\0\7\70\1\203\7\70\4\0"+
    "\16\70";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4418];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\1\1\11\25\1\1\0\4\1\4\11\45\1"+
    "\1\11\1\0\72\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public OCL_Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public OCL_Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 32: 
          { return symbol(OclSym.SELECT);
          }
        case 39: break;
        case 12: 
          { return symbol(OclSym.DIVIDE);
          }
        case 40: break;
        case 5: 
          { return symbol(OclSym.COMMA);
          }
        case 41: break;
        case 30: 
          { return symbol(OclSym.FALSE);
          }
        case 42: break;
        case 15: 
          { return symbol(OclSym.DOTDOT);
          }
        case 43: break;
        case 26: 
          { return symbol(OclSym.TYPE, yytext());
          }
        case 44: break;
        case 3: 
          { return symbol(OclSym.RPAREN);
          }
        case 45: break;
        case 36: 
          { return symbol(OclSym.OCL_IS_NEW);
          }
        case 46: break;
        case 37: 
          { return symbol(OclSym.INCLUDING);
          }
        case 47: break;
        case 18: 
          { return symbol(OclSym.RELOP, OclSym.GE);
          }
        case 48: break;
        case 16: 
          { return symbol(OclSym.RELOP, OclSym.LE);
          }
        case 49: break;
        case 35: 
          { System.out.println(yytext());return symbol(OclSym.CONTEXT);
          }
        case 50: break;
        case 10: 
          { return symbol(OclSym.PLUS);
          }
        case 51: break;
        case 27: 
          { return symbol(OclSym.SIZE);
          }
        case 52: break;
        case 23: 
          { return symbol(OclSym.TRUE);
          }
        case 53: break;
        case 25: 
          { return symbol(OclSym.ELSE);
          }
        case 54: break;
        case 33: 
          { return symbol(OclSym.FOR_ALL);
          }
        case 55: break;
        case 8: 
          { return symbol(OclSym.RELOP, OclSym.GT);
          }
        case 56: break;
        case 24: 
          { return symbol(OclSym.THEN);
          }
        case 57: break;
        case 11: 
          { return symbol(OclSym.MULT);
          }
        case 58: break;
        case 7: 
          { return symbol(OclSym.RELOP, OclSym.LT);
          }
        case 59: break;
        case 38: 
          { return symbol(OclSym.EXCLUDING);
          }
        case 60: break;
        case 20: 
          { System.out.println(yytext());return symbol(OclSym.INV);
          }
        case 61: break;
        case 31: 
          { return symbol(OclSym.EXISTS);
          }
        case 62: break;
        case 4: 
          { return symbol(OclSym.COLON);
          }
        case 63: break;
        case 28: 
          { return symbol(OclSym.SELF);
          }
        case 64: break;
        case 17: 
          { return symbol(OclSym.RELOP, OclSym.NEQUAL);
          }
        case 65: break;
        case 21: 
          { return symbol(OclSym.STRING, yytext());
          }
        case 66: break;
        case 2: 
          { return symbol(OclSym.LPAREN);
          }
        case 67: break;
        case 29: 
          { return symbol(OclSym.ENDIF);
          }
        case 68: break;
        case 6: 
          { return symbol(OclSym.RELOP, OclSym.EQUAL);
          }
        case 69: break;
        case 22: 
          { return symbol(OclSym.SET);
          }
        case 70: break;
        case 13: 
          { return symbol(OclSym.ID, yytext());
          }
        case 71: break;
        case 14: 
          { /*return*/ symbol(OclSym.NUMERO, new Integer(yytext()));
          }
        case 72: break;
        case 19: 
          { return symbol(OclSym.IF);
          }
        case 73: break;
        case 1: 
          { 
          }
        case 74: break;
        case 34: 
          { return symbol(OclSym.IMPLIES);
          }
        case 75: break;
        case 9: 
          { return symbol(OclSym.MINUS);
          }
        case 76: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(OclSym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
