
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 28 03:45:38 BRT 2011
//----------------------------------------------------

package compil.inv.parser;

/** CUP generated interface containing symbol constants. */
public interface OclSym {
  /* terminals */
  public static final int RARROW = 21;
  public static final int NUMERO = 50;
  public static final int DIVIDE = 7;
  public static final int MULT = 6;
  public static final int GE = 20;
  public static final int ATSIGN = 27;
  public static final int LPAREN = 8;
  public static final int SEMI = 2;
  public static final int INV = 29;
  public static final int MINUS = 5;
  public static final int BAR = 26;
  public static final int RPAREN = 9;
  public static final int LT = 17;
  public static final int TYPE = 38;
  public static final int COMMA = 14;
  public static final int SEMICOL = 25;
  public static final int IMPLIES = 44;
  public static final int FOR_ALL = 32;
  public static final int DOTDOT = 22;
  public static final int SELECT = 30;
  public static final int PLUS = 4;
  public static final int IF = 40;
  public static final int ID = 49;
  public static final int RELOP = 43;
  public static final int DOT = 23;
  public static final int CONTEXT = 28;
  public static final int LE = 19;
  public static final int EOF = 0;
  public static final int EQUAL = 15;
  public static final int TRUE = 47;
  public static final int SIZE = 36;
  public static final int POUND = 24;
  public static final int error = 1;
  public static final int SELF = 39;
  public static final int LCURLY = 12;
  public static final int EXISTS = 31;
  public static final int INCLUDING = 33;
  public static final int OCL_IS_NEW = 35;
  public static final int RCURLY = 13;
  public static final int LBRACK = 10;
  public static final int EXCLUDING = 34;
  public static final int COLON = 3;
  public static final int ENDIF = 45;
  public static final int ELSE = 42;
  public static final int RBRACK = 11;
  public static final int NEQUAL = 16;
  public static final int THEN = 41;
  public static final int STRING = 37;
  public static final int FALSE = 48;
  public static final int GT = 18;
  public static final int SET = 46;
}

