
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 27 21:29:07 BRT 2011
//----------------------------------------------------

package compil.inv.parser;

/** CUP generated interface containing symbol constants. */
public interface OclSym {
  /* terminals */
  public static final int error = 1;
  public static final int ANY = 2;
  public static final int EOF = 0;
}

