
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 04 20:58:46 BRT 2011
//----------------------------------------------------

package compil.inv.parser;

/** CUP generated class containing symbol constants. */
public class OCLSym {
  /* terminals */
  public static final int RARROW = 24;
  public static final int FORALL = 36;
  public static final int NUMERO = 43;
  public static final int EXCLUDES = 35;
  public static final int DIVIDE = 17;
  public static final int MULT = 16;
  public static final int GE = 11;
  public static final int XOR = 5;
  public static final int LPAREN = 21;
  public static final int INV = 3;
  public static final int MINUS = 15;
  public static final int BAR = 26;
  public static final int RPAREN = 22;
  public static final int NOT = 7;
  public static final int AND = 6;
  public static final int INCLUDES = 34;
  public static final int LT = 8;
  public static final int RCOL = 39;
  public static final int OR = 4;
  public static final int COMMA = 23;
  public static final int SEMICOL = 18;
  public static final int IMPLIES = 32;
  public static final int SELECT = 37;
  public static final int PLUS = 14;
  public static final int IF = 28;
  public static final int ID = 42;
  public static final int DOT = 25;
  public static final int CONTEXT = 2;
  public static final int LE = 10;
  public static final int EOF = 0;
  public static final int EQUAL = 12;
  public static final int SIZE = 33;
  public static final int error = 1;
  public static final int EXISTS = 38;
  public static final int COLON = 19;
  public static final int ENDIF = 31;
  public static final int ELSE = 30;
  public static final int DCOLON = 20;
  public static final int NEQUAL = 13;
  public static final int THEN = 29;
  public static final int LCOL = 40;
  public static final int STRING = 27;
  public static final int INCLUDESALL = 41;
  public static final int GT = 9;
}

